### ISSUE TITLE
login project

### ISSUE THREAD

**Issue by seble2000** [seble2000/QA06ENGINNER#1]

**Comment by bonsabk** [comment]
working on it. Give me about 10 min and I will send you the final report. Thank you

**Comment by seble2000** [comment]
ok i will wait

**Comment by bonsabk** [comment]
Here is my final report. I am waiting for your feedback. Thank you!

**Comment by bonsabk** [comment]
still waiting

**Comment by seble2000** [comment]
good job danny.
